[package]
template = true
keywords = ["Kind/Sample", "Type/ManualTrigger", "Category/Integration"]
org = "choreo"
displayName = "Ronin Invoices to Quickbooks Online Invoices"
name = "ronin_invoices_to_quickbooks_online_invoices"
icon = "icon.png"
description = "Creates new Quickbooks online invoices from Ronin invoices."
distribution = "2201.4.1"
version = "3.2.0"
[build-options]
observabilityIncluded = true
