[package]
template = true
keywords = ["Kind/Sample", "Type/ManualTrigger", "Category/Integration"]
org = "choreo"
displayName = "COVID-19 Statistics to Email"
name = "covid19_statistics_to_email"
icon = "icon.png"
description = "Calculates COVID-19 cases per million in a specific country and send an email"
distribution = "2201.4.1"
version = "3.2.0"
[build-options]
observabilityIncluded = true
