[package]
template = true
keywords = ["Kind/Sample", "Type/Webhook", "Category/Integration", "Internal/http"]
org = "choreo"
displayName = "Slack Channel New Message to ServiceNow Case"
name = "slack_new_message_to_servicenow_case"
icon = "icon.png"
description = "Creates a ServiceNow case when a new message is posted to a specific Slack channel"
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
