[package]
template = true
keywords = ["Kind/Sample", "Type/Webhook/Integration", "Category/Integration"]
org = "choreo"
displayName = "Salesforce Record Update to Google Sheets New Row"
name = "sfdc_update_record_to_gsheet_new_row"
icon = "icon.png"
description = "Adds details to a spreadsheet row when a new record is updated in a specific Salesforce account"
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
