[package]
template = true
keywords = ["Kind/Sample", "Type/ManualTrigger", "Category/Integration"]
org = "choreo"
displayName = "Xero Sales Invoices to Gmail"
name = "xero_sales_invoices_to_gmail"
icon = "icon.png"
description = "Send a summary of new Xero invoices created in the past week as an email via Gmail"
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
