[package]
template = true
keywords = ["Kind/Sample", "Type/Webhook", "Category/Integration", "Internal/http"]
org = "choreo"
displayName = "Gmail New Attachment to Google Drive"
name = "gmail_new_attachment_to_drive"
icon = "icon.png"
description = "Upload attachments to Google drive when a new Gmail comes with attachments"
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
