[package]
template = true
keywords = ["Kind/Sample", "Type/ManualTrigger", "Category/Integration"]
org = "choreo"
displayName = "Google Drive files to Microsoft OneDrive files"
name = "gdrive_files_to_microsoft_onedrive_files"
icon = "icon.png"
description = "Sync Google Drive files to Microsoft OneDrive"
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
