[package]
template = true
keywords = ["Kind/Sample", "Type/Webhook", "Category/Integration", "Internal/http"]
org = "choreo"
displayName = "Google Sheets New Row to Salesforce New Lead"
name = "gsheet_new_row_to_sfdc_new_lead"
icon = "icon.png"
description = "Adds a lead in Salesforce when new lead details are added to a spreadsheet row"
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
