[package]
template = true
keywords = ["Kind/Sample", "Type/Webhook", "Category/Integration"]
org = "choreo"
displayName = "Salesforce New Lead to Mailchimp Subscribers List"
name = "sfdc_new_lead_to_mailchimp_subscribers"
icon = "icon.png"
description = "Create a new contact in Mailchimp subscribers list when a new lead is created in a specific Salesforce account"
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
