[package]
template = true
keywords = ["Kind/Sample", "Type/Webhook", "Category/Integration", "Internal/http"]
org = "choreo"
displayName = "Gmail New Attachment to Amazon S3"
name = "gmail_new_attachment_to_amazon_s3"
icon = "icon.png"
description = "Upload attachments to Amazon S3 when a new Gmail email is received with attachments"
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
