[package]
template = true
keywords = ["Kind/Sample", "Type/Webhook", "Category/Integration", "Internal/http"]
org = "choreo"
displayName = "GitHub New Release to Slack Channel Message"
name = "github_release_to_slack"
icon = "icon.png"
description = "Posts a message to a Slack channel when a release is made in a specific GitHub repository"
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
