[package]
template = true
keywords = ["Kind/Sample", "Type/Webhook", "Category/Integration", "Internal/http"]
org = "choreo"
displayName = "GitHub Issue Assigned to Twilio SMS"
name = "github_issue_assigned_to_twilio_sms"
icon = "icon.png"
description = "Sends a Twilio SMS to a phone number when a GitHub issue is assigned to a particular user"
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
