[package]
template = true
keywords = ["Kind/Sample", "Type/ManualTrigger", "Category/Integration"]
org = "choreo"
displayName = "Microsoft Excel Row to Salesforce Lead Conversion"
name = "microsoft_excel_to_salesforce_convertlead"
icon = "icon.png"
description = "Convert Salesforce Lead from the details provided in Microsoft Excel Worksheet Row"
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
