[package]
template = true
keywords = ["Kind/Sample", "Type/Webhook", "Category/Integration"]
org = "choreo"
displayName = "Salesforce New Hot Lead to Slack Channel Message"
name = "sfdc_hot_lead_to_slack"
icon = "icon.png"
description = "Posts a message to a Slack channel when a new hot lead is created in a specific Salesforce account"
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
