[package]
template = true
keywords = ["Kind/Sample", "Type/Webhook", "Category/Integration"]
org = "choreo"
displayName = "Salesforce Outbound Message to Google Sheets Row"
name = "sfdc_outbound_msg_to_gsheet"
icon = "icon.png"
description = "Adds details to a spreadsheet row when a new outbound message is received from a Salesforce account"
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
