[package]
template = true
keywords = ["Kind/Sample", "Type/Webhook", "Category/Integration", "Internal/http"]
org = "choreo"
displayName = "Google Calendar Event to Microsoft Teams Channel Message"
name = "gcalendar_new_event_to_msteams_message"
icon = "icon.png"
description = "Sends a message to Microsoft Teams channel when a new event is created in a specific Google Calendar"
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
