[package]
template = true
keywords = ["Kind/Sample", "Type/Service", "Category/Service", "Internal/http"]
org = "choreo"
displayName = "Error Handling"
name = "error_handling"
icon = "icon.png"
description = "Handle errors at different levels of granularities"
distribution = "2201.3.1"
version = "3.1.1"
[build-options]
observabilityIncluded = true
