[package]
template = true
keywords = ["Kind/Sample", "Type/ScheduledTask", "Category/Integration"]
org = "choreo"
displayName = "Send a Slack message with weather updates to a particular city periodically"
name = "interzoid_weather_update_to_slack_message"
icon = "icon.png"
description = "Send a Slack message with detailed weather report periodically"
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
