[package]
template = true
keywords = ["Kind/Sample", "Type/Service", "Category/Service", "Internal/http"]
org = "choreo"
displayName = "Echo Service"
name = "echo_service"
icon = "icon.png"
description = "Responds with the same message received via an HTTP POST"
distribution = "2201.3.1"
version = "3.1.1"
[build-options]
observabilityIncluded = true
