[package]
template = true
keywords = ["Kind/Sample", "Type/Webhook", "Category/Integration"]
org = "choreo"
displayName = "Salesforce Opportunity Update to Twilio SMS"
name = "sfdc_opportunity_update_to_twilio_sms"
icon = "icon.png"
description = "Sends a Twilio SMS to a phone number when an opportunity is updated in a specific Salesforce account"
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
