[package]
template = true
keywords = ["Kind/Sample", "Type/Service", "Category/Service", "Internal/http"]
org = "choreo"
displayName = "Database Connection"
name = "database"
icon = "icon.png"
description = "Reads data from a MySQL database and returns a JSON response"
distribution = "2201.3.1"
version = "3.1.1"
[build-options]
observabilityIncluded = true
