[package]
template = true
keywords = ["Kind/Sample", "Type/Service", "Category/Integration", "Internal/http"]
org = "choreo"
displayName = "SCIM User Details To Google Sheets Row"
name = "scim_user_details_to_google_sheet_row"
icon = "icon.png"
description = "Add google sheet rows according to the user details coming into the service endpoint"
distribution = "2201.3.1"
version = "3.1.1"
[build-options]
observabilityIncluded = true
