[package]
template = true
keywords = ["Kind/Sample", "Type/Service", "Category/Service", "Internal/http"]
org = "choreo"
displayName = "Hello World"
name = "hello_world"
icon = "icon.png"
description = "Responds with the Hello World message"
distribution = "2201.3.1"
version = "3.1.1"
[build-options]
observabilityIncluded = true
