[package]
template = true
keywords = ["Kind/Sample", "Type/Service", "Category/Service", "Internal/http"]
org = "choreo"
displayName = "Guaranteed Delivery using Azure Service Bus"
name = "guaranteed_delivery"
icon = "icon.png"
description = "Provides guaranteed delivery for messages in ASB queue"
distribution = "2201.3.1"
version = "3.1.1"
[build-options]
observabilityIncluded = true
