[package]
template = true
keywords = ["Kind/Sample", "Type/Service", "Category/Service", "Internal/http"]
org = "choreo"
displayName = "HTTP Header Manipulation"
name = "header_manipulation"
icon = "icon.png"
description = "Manipulates HTTP headers to implement HTTP basic authentication scenarios"
distribution = "2201.3.1"
version = "3.1.1"
[build-options]
observabilityIncluded = true
