[package]
template = true
keywords = ["Kind/Sample", "Type/Webhook", "Category/Integration"]
org = "choreo"
displayName = "Salesforce Record Update to Google Sheets Row Update"
name = "sfdc_record_update_to_gsheet_update_row"
icon = "icon.png"
description = "Updates details in a spreadsheet row when a record is updated in a specific Salesforce account"
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
