[package]
template = true
keywords = ["Kind/Sample", "Type/Webhook", "Category/Integration"]
org = "choreo"
displayName = "Send Marketing Email to Salesforce New Lead"
name = "marketing_email_to_sfdc_new_lead"
icon = "icon.png"
description = "Send a marketing email via Gmail to new Salesforce lead when it is created in a specific Salesforce account"
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
