[package]
template = true
keywords = ["Kind/Sample", "Type/ManualTrigger", "Category/Integration"]
org = "choreo"
displayName = "Evenbrite Event Attendees to Mailchimp Subscribers"
name = "eventbrite_event_attendees_to_mailchimp_subscribers"
icon = "icon.png"
description = "Adds new Eventbrite event attendees to a Mailchimp audience(subscriber list) for an Eventbrite event."
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
