[package]
template = true
keywords = ["Kind/Sample", "Type/Webhook", "Category/Integration", "Internal/http"]
org = "choreo"
displayName = "SMS Voting Survey to Google Sheets Summary"
name = "twilio_sms_to_gsheet"
icon = "icon.png"
description = "A survey to find out the best language for building microservices out of a set of given languages"
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
