[[dependency]]
org = "ballerina"
name = "googleapis.calendar"
version = "0.1.6-SNAPSHOT"

[[dependency]]
org = "ballerina"
name = "twilio"
version = "0.99.9-SNAPSHOT"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-alpha8"
