[package]
template = true
keywords = ["Kind/Sample", "Type/Webhook", "Category/Integration"]
org = "choreo"
displayName = "Salesforce Opportunity 'Closed Won' to Slack Channel Message"
name = "sfdc_opportunity_closedwon_to_slack"
icon = "icon.png"
description = "Posts a message to a Slack channel when an opportunity is 'Closed Won' in a specific Salesforce account"
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
