[package]
template = true
keywords = ["Kind/Sample", "Type/ManualTrigger", "Category/Integration"]
org = "choreo"
displayName = "News API Headlines to Email"
name = "newsapi_headlines_to_email"
icon = "icon.png"
description = "Send an email with list of top headlines by News API."
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
