name: Build samples

on:
  workflow_dispatch:

jobs:
  build_samples:
    name: Build Samples
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['samples/integrations/gcalendar-to-twilio', 'twilio-sms-to-gsheet'] }
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch connector depdencies
      working-directory: ./scripts/sample-tests
      env:
        packageUser: ${{ github.actor }}
        packagePAT: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew build
    - name: Build samples
      uses: ballerina-platform/ballerina-action@nightly
      working-directory: ${{ matrix.dir }}
      run: pwd
      with:
        args:
          build
      